### ISSUE TITLE
Fakenews.de

### ISSUE THREAD

**Issue by joe-haw** [Akamaru/Pi-Hole-Lists#10]
I was looking through the lists and found that several hosts included in the fakenews.de list are in fact not fake news sites.

How come `afd.de` (the official website of a German political party) and `deutsch.rt.com` (the german website for the media network RT, ran by the Russian government) are considered sources of fake news?

What is taken into consideration for deciding whether a site shall be included in that list?

**Comment by Akamaru** [comment]
AfD are on this list because they shared a lot of fake news on social media and on their website too. They are right-winged. 
rt is on this list because its rt ¯\_(ツ)_/¯
as you said:
>ran by the Russian government

after all, these are my private lists and I only share them if someone interested in this lists.
if you dont wont to block these domains, whitelist them or dont use my lists.
everyone can fork these lists and add/remove what they want.
