### ISSUE TITLE
events.gfe.nvidia.com

### ISSUE THREAD

**Issue by p1r473** [Akamaru/Pi-Hole-Lists#16]
Please remove this from list
Needed for Nvidia driver software

**Comment by Akamaru** [comment]
Hi, I'm using Nvidia GeForce since years and its still working for me.
I tried to login (works), check updates (works), download update (works) and install update (works).
I tried the game optimize feature, it works. And I tried the game overlay with recording and streaming. It works.

So what does not working for you?

**Comment by p1r473** [comment]
Closing for now, will re-open if I can figure out what it broke.
Thanks
